### ISSUE TITLE
Install failing with python setup.py egg_info" failed with error code 1 in /private/var/folders/58/_zw7g73x1lv5zt4bjrl3nwsc0000gn/T/pip-install-rd1itnkv/psycopg2/

### ISSUE THREAD

**Issue by charlbury** [afourmy/flask-gentelella#14]
The `pip install -r requirements.txt` is failing when installing psycopg2.

```
Collecting psycopg2
  Using cached https://files.pythonhosted.org/packages/52/be/f898e712f5f08131d651a62754fca82a1deb42e4e9889ad01932f770a2be/psycopg2-2.8.1.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'

    Error: pg_config executable not found.

    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.

    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.

    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).


    ----------------------------------------
Command "python setup.py egg_info" failed with error code
```

Trying to get flask to run the app then fails with a first message of:

```
Error: While importing "gentelella", an ImportError was raised:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
  File "/Users/steve/dev/flask-gentelella/gentelella.py", line 1, in <module>
    from flask_migrate import Migrate
ModuleNotFoundError: No module named 'flask_migrate'
```

**Comment by afourmy** [comment]
This is not a problem with flask-gentelella but with your environment, see stackoverflow for solutions.
The fact that flask_migrate module is not found is simply a consequence of psycopg2 installation failing.
