### ISSUE TITLE
could not translate host name "db" to address: Unknown host

### ISSUE THREAD

**Issue by robertocrr1** [afourmy/flask-gentelella#18]
I am trying to run the app in a windows 10 pc.
Afer running the command "flask run" the app will run with host = 120.0.0.1:5000.
When I try to access the address from a browser then following error comes:

 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
Exception on / [GET]
Traceback (most recent call last):
  File "c:\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 2262, in _wrap_pool_connect
    return fn()
  File "c:\anaconda3\lib\site-packages\sqlalchemy\pool\base.py", line 354, in connect
    return _ConnectionFairy._checkout(self)
  File "c:\anaconda3\lib\site-packages\sqlalchemy\pool\base.py", line 751, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "c:\anaconda3\lib\site-packages\sqlalchemy\pool\base.py", line 483, in checkout
    rec = pool._do_get()
  File "c:\anaconda3\lib\site-packages\sqlalchemy\pool\impl.py", line 138, in _do_get
    self._dec_overflow()
  File "c:\anaconda3\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "c:\anaconda3\lib\site-packages\sqlalchemy\util\compat.py", line 129, in reraise
    raise value
  File "c:\anaconda3\lib\site-packages\sqlalchemy\pool\impl.py", line 135, in _do_get
    return self._create_connection()
  File "c:\anaconda3\lib\site-packages\sqlalchemy\pool\base.py", line 299, in _create_connection
    return _ConnectionRecord(self)
  File "c:\anaconda3\lib\site-packages\sqlalchemy\pool\base.py", line 428, in __init__
    self.__connect(first_connect_check=True)
  File "c:\anaconda3\lib\site-packages\sqlalchemy\pool\base.py", line 630, in __connect
    connection = pool._invoke_creator(self)
  File "c:\anaconda3\lib\site-packages\sqlalchemy\engine\strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "c:\anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 453, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "c:\anaconda3\lib\site-packages\psycopg2\__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "db" to address: Unknown host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\anaconda3\lib\site-packages\flask\app.py", line 1945, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "c:\anaconda3\lib\site-packages\flask\app.py", line 1993, in try_trigger_before_first_request_functions
    func()
  File "C:\Users\ruval\flask-gentelella\app\__init__.py", line 27, in initialize_database
    db.create_all()
  File "c:\anaconda3\lib\site-packages\flask_sqlalchemy\__init__.py", line 1039, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "c:\anaconda3\lib\site-packages\flask_sqlalchemy\__init__.py", line 1031, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "c:\anaconda3\lib\site-packages\sqlalchemy\sql\schema.py", line 4287, in create_all
    ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
  File "c:\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 2032, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "c:\anaconda3\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "c:\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 2024, in _optional_conn_ctx_manager
    with self._contextual_connect() as conn:
  File "c:\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 2226, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "c:\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 2266, in _wrap_pool_connect
    e, dialect, self
  File "c:\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1536, in _handle_dbapi_exception_noconnection
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "c:\anaconda3\lib\site-packages\sqlalchemy\util\compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "c:\anaconda3\lib\site-packages\sqlalchemy\util\compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "c:\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 2262, in _wrap_pool_connect
    return fn()
  File "c:\anaconda3\lib\site-packages\sqlalchemy\pool\base.py", line 354, in connect
    return _ConnectionFairy._checkout(self)
  File "c:\anaconda3\lib\site-packages\sqlalchemy\pool\base.py", line 751, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "c:\anaconda3\lib\site-packages\sqlalchemy\pool\base.py", line 483, in checkout
    rec = pool._do_get()
  File "c:\anaconda3\lib\site-packages\sqlalchemy\pool\impl.py", line 138, in _do_get
    self._dec_overflow()
  File "c:\anaconda3\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "c:\anaconda3\lib\site-packages\sqlalchemy\util\compat.py", line 129, in reraise
    raise value
  File "c:\anaconda3\lib\site-packages\sqlalchemy\pool\impl.py", line 135, in _do_get
    return self._create_connection()
  File "c:\anaconda3\lib\site-packages\sqlalchemy\pool\base.py", line 299, in _create_connection
    return _ConnectionRecord(self)
  File "c:\anaconda3\lib\site-packages\sqlalchemy\pool\base.py", line 428, in __init__
    self.__connect(first_connect_check=True)
  File "c:\anaconda3\lib\site-packages\sqlalchemy\pool\base.py", line 630, in __connect
    connection = pool._invoke_creator(self)
  File "c:\anaconda3\lib\site-packages\sqlalchemy\engine\strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "c:\anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 453, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "c:\anaconda3\lib\site-packages\psycopg2\__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "db" to address: Unknown host

(Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by snhobbs** [comment]
The default settings seem to be using postgres (psycopg2 is for this). By changing the variable GENTELELLA_CONFIG_MODE to DEBUG (export GENTELELLA_CONFIG_MODE=DEBUG) the sqlite will be used. This can also be fixed by changing the value in the .env file.

**Comment by pwhartnett** [comment]
Hi - I am having this same problem with the "could not translate host name "db" to address: Unknown host"
Can you please tell me is this is correct change the .env file to the following?

GENTELELLA_CONFIG_MODE=DEBUG
POSTGRES_USER=gentelella
POSTGRES_PASSWORD=gentelella
POSTGRES_DB=gentelella

This still does not work for me? Seems to be a new issue. 

Thank you in advance!

**Comment by snhobbs** [comment]
Thats the correct change and I have it working on Ubuntu 20.04 (python 3.8.5, flask 1.1.2) with a virtualenv. Check that you have python-dotenv installed which parses these files. You could start by setting the environment manually with one of these:
(Windows) set GENTELELLA_CONFIG_MODE=DEBUG
(Unix) export GENTELELLA_CONFIG_MODE=DEBUG
(Powershell) $env:GENTELELLA_CONFIG_MODE = "DEBUG"
