### ISSUE TITLE
running tests in docker container?

### ISSUE THREAD

**Issue by jminardi** [afourmy/flask-gentelella#3]
Can someone give me pointers to getting the tests to run in a docker container?

Here is the Dockerfile I am using:

```Dockerfile
FROM python:3.6
COPY requirements.txt .
COPY requirements_dev.txt .
COPY ./ /app
RUN pip install -r requirements_dev.txt
EXPOSE 5000
WORKDIR /app/source
```

And the docker-compose.yml file I am using:

```yaml
version: "2.1"

services:
    web:
        container_name: web
        build: .
        command: gunicorn --log-file=- --bind 0.0.0.0:5000 --workers 5 app:app
        ports:
            - "5000:5000"
        env_file: secrets.env
        environment:
            - DEBUG=${DEBUG:-0}
        restart: unless-stopped
        links:
            - db
    db:
        container_name: db
        image: postgres:10.4
        env_file: secrets.env
        restart: unless-stopped
        volumes:
            - ./pgdata:/var/lib/postgresql/data
```

Here is the command I am using to run the tests:

`docker-compose run web coverage run --source=../app -m pytest ../tests/`

And this is the error I am getting:

```bash
Starting db ... done
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/_pytest/config/__init__.py", line 372, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/app/tests')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/_pytest/config/__init__.py", line 403, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/app/tests/conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/_pytest/config/__init__.py", line 409, in _importconftest
    mod = conftestpath.pyimport()
  File "/usr/local/lib/python3.6/site-packages/py/_path/local.py", line 686, in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
py._path.local.LocalPath.ImportMismatchError: ('conftest', '/Users/jack/code/flask-gentelella/tests/conftest.py', local('/app/tests/conftest.py'))
ERROR: could not load /app/tests/conftest.py
```

Since I am running inside a Docker container I am confused as to how it is even detecting `/Users/jack/code/flask-gentelella/tests/conftest.py` (which is on my host machine).

I found references online saying I need to make sure to delete any `__pycache__` folders before building the docker image, but that did not help. I also made sure there was no volume sharing between the container and my host machine.

Any help would be appreciated.

**Comment by jminardi** [comment]
Ahh, I found another __pycache__ and .cache folder deeper in the directories. Removing those fixed my issues.

On a related note, does anyone know why the following line isn't working for me?

```python
# prevent python from writing *.pyc files / __pycache__ folders
sys.dont_write_bytecode = True
```

**Comment by afourmy** [comment]
@jminardi It did work in previous versions of the project because I was using python to start the application (via `app.run` (deprecated)), but it doesn't work when using `flask run` (the proper way, see https://softwareengineering.stackexchange.com/questions/326517/why-is-flask-cli-recommended-over-flask-run).

I removed the dont_write_bytecode initialization from the code (in most cases, it is not relevant). Can you try to set the `PYTHONDONTWRITEBYTECODE` environment variable to 1 instead ? Using a environment variable should be the right way to do that with `flask run`.

Also: can I add (or can you make a PR adding) your `docker-compose` example to the main repository ? I believe it would be very useful for those who don't know how to set up a postgresql database with docker.

**Comment by jminardi** [comment]
HI @afourmy thanks for the information.

Regarding docker-compose, I'd be happy to add my file as an example. In my compose file I actually have 2 more services: `pgadmin` for db management/inspection and `traefik` for automatic SSL certs from letsencrypt. Do you think I should include those as well?

**Comment by afourmy** [comment]
@jminardi Yes you can include them too, I'm sure some people will find it useful. Thanks :)
