### ISSUE TITLE
Why do I get a 500 error after login?

### ISSUE THREAD

**Issue by aguillenv** [afourmy/flask-gentelella#7]
I've cloned the repository locally and install everything without any issue. I've created a new user. When I'm trying to login launch an internal server error. The error in the console is this one:

> Exception on /login [POST]
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/home/alejandro/MATIS/brain-mixer-project/flask-gentelella/app/base/routes.py", line 48, in login
>     if user and checkpw(password.encode('utf8'), user.password):
>   File "/usr/local/lib/python2.7/dist-packages/bcrypt/__init__.py", line 101, in checkpw
>     raise TypeError("Unicode-objects must be encoded before checking")
> TypeError: Unicode-objects must be encoded before checking`

The weird thing is that when I've tried the docker option it works fine.

Could you help me with this?

**Comment by afourmy** [comment]
I recently switched to bcrypt hashing for the authentication, that may have broken compatibility with python 2 (I also removed py27 from travis which explains why the build is passing).  Can you try with py36 instead and confirm its ok

Thanks
